library("rjson")
library("jsonlite")
library("httr")
library("ggthemes")
library("scales")
library("stringr")
library("ggvis")
library("reshape")
library("dplyr")
french <- function(x) str_trim(format(x, big.mark = " ", decimal.mark = ",", scientific = FALSE))
